# -*- coding: utf-8 -*-
"""portfolio_cedears.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DYZss-osjWtvYEeAydHU1RxJZm8T_8_
"""

import yfinance as yf

import matplotlib.pyplot as plt

import pandas as pd

import numpy as np

tickers = ['AAPL', 'GOOGL', 'MSFT', 'AMZN', 'JPM']  # Ejemplo de tickers de acciones

stock_data = yf.download(tickers, start='2020-01-01', end='2023-01-01')['Adj Close']

print(stock_data.head())

plt.figure(figsize=(14, 7))
for ticker in tickers:
    plt.plot(stock_data.index, stock_data[ticker], label=ticker)

daily_returns = stock_data.pct_change()

plt.figure(figsize=(14, 7))
for ticker in tickers:
    plt.plot(stock_data.index, daily_returns[ticker], label=ticker)

# Estadísticas descriptivas
print(stock_data.describe())

plt.figure(figsize=(14, 7))
for ticker in tickers:
    plt.plot(stock_data.index, stock_data[ticker], label=ticker)
    plt.plot(stock_data.index, stock_data[ticker].rolling(window=30).mean(), label=f'{ticker} - Media Móvil 30 días')

max_growth = stock_data.pct_change().max()

plt.figure(figsize=(10, 6))
plt.pie(max_growth, labels=max_growth.index, autopct='%1.1f%%', startangle=140)
plt.title('Mayor Crecimiento para Cada Acción')
plt.show()

